name: Tezos Init Containers CI

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: 'release'
        description: 'Tezos version'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push tezos Node Configurator
        id: docker_build_tezos_node_configurator
        uses: docker/build-push-action@v2
        with:
          context: ./node-configurator
          platforms: linux/amd64
          build-args: |
            VERSION=${{ github.event.inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/marigold-dev/tezos-node-configurator:${{ github.event.inputs.version }}
            ghcr.io/marigold-dev/tezos-node-configurator:${{ github.sha }}

      - name: Build and push tezos Snapshot Downloader
        id: docker_build_tezos_snapshot_downloader
        uses: docker/build-push-action@v2
        with:
          context: ./snapshot-downloader
          platforms: linux/amd64
          build-args: |
            VERSION=${{ github.event.inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/marigold-dev/tezos-snapshot-downloader:${{ github.event.inputs.version }}
            ghcr.io/marigold-dev/tezos-snapshot-downloader:${{ github.sha }}
